name: rich_text_view
description: A simple yet powerful rich text view that supports mention, hashtag, emial, url and see more.
version: 1.0.0
homepage: https://github.com/nelstein/rich_text_view

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:

